DROP TABLE IF EXISTS Player_Data;
CREATE TABLE IF NOT EXISTS Player_Data(
    id INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    player INT NOT NULL,
    season INT NOT NULL,
    age INT NOT NULL,
    pra DOUBLE PRECISION NOT NULL,
    stock DOUBLE PRECISION NOT NULL,
    ts DOUBLE PRECISION NOT NULL,
    useage DOUBLE PRECISION NOT NULL,
    mins DOUBLE PRECISION NOT NULL,
    per DOUBLE PRECISION NOT NULL,
    drtg INT NOT NULL,
    FOREIGN KEY (player) REFERENCES Player_Info(player_id)
);