INSERT INTO Teams (city, name) VALUES
('New York', 'Knicks'),
('Detriot', 'Pistons'),
('Cleveland','Cavaliers'),
('Boston','Celtics'),
('Toranto','Raptors'),
('Atlanta','Hawks'),
('Philadelphia','76ers'),
('Orlando','Magic'),
('Charlotte','Hornets'),
('Miami','Heat'),
('Milwaukee','Bucks'),
('Chicago','Bulls'),
('Brooklyn','Nets'),
('Indiana','Pacers'),
('Washington','Wizards'),

('Oklahoma City','Thunder'),
('San Antonino','Spurs'),
('Denver','Nuggets'),
('Los Angeles','Lakers'),
('Houston','Rockets'),
('Minnesoda','Timberwolves'),
('Portland','Trail Blazers'),
('Phoenix','Suns'),
('Los Angeles','Clippers'),
('Golden State','Warriors'),
('New Orleans','Pelicans'),
('Dallas','Mavericks'),
('Memphis','Grizzlies'),
('Sacramento','Kings'),
('Utah','Jazz');